### ISSUE TITLE
3DS2 - Argument 1 passed to ServicesContainer::__construct() must be an instance of IPaymentGateway, null given

### ISSUE THREAD

**Issue by seonzoo** [globalpayments/php-sdk#38]
Hello, I've been following the api documentation from here: https://developer.globalpay.com/#!/ecommerce/3d-secure-version2

So far, using the code samples has been mostly successful, but I'm now stuck at the Initiate Authentication Request with this error:

```
Type error: Argument 1 passed to GlobalPayments\Api\ServicesContainer::__construct() must be an instance of GlobalPayments\Api\Gateways\IPaymentGateway, null given, called in /opt/sites/3ds2test/vendor/globalpayments/php-sdk/src/ServicesContainer.php on line 70
#0 /opt/sites/3ds2test/vendor/globalpayments/php-sdk/src/ServicesContainer.php(70): GlobalPayments\Api\ServicesContainer->__construct(NULL)
#1 /opt/sites/3ds2test/vendor/globalpayments/php-sdk/src/Builders/Secure3dBuilder.php(1122): GlobalPayments\Api\ServicesContainer::instance()
#2 /opt/sites/3ds2test/app/Http/Controllers/ScaController.php(268): GlobalPayments\Api\Builders\Secure3dBuilder->execute('TWO')
```

my code is very similar to the example...

```
    $threeDSecureData = Secure3dService::initiateAuthentication($card, $threeDS)
    ->withAmount($amount)
    ->withCurrency($currency)
    ->withOrderCreateDate(date("Y-m-d H:i:s"))
    ->withAddress($billingAddress, AddressType::BILLING)
    ->withAddress($shippingAddress, AddressType::SHIPPING)
    ->withBrowserData($browserData)
    ->withMethodUrlCompletion(MethodUrlCompletion::YES)
    ->withMobileNumber($callingCode, $phone)
    ->execute(Secure3dVersion::TWO);
```

I've caught a couple of spelling mistakes from the documentation, but am not sure how to fix this... any advice would be very much appreciated.

**Comment by seonzoo** [comment]
oh I see now, the Services config was missing from the initiateAuthentication route...

will close this issue once I get past this helpful error:

```
Status Code: 400 - Format of one or more Data Elements is Invalid according to the Specification
```
